//the config is autogenerated from mongo at the initialization
//see models/config and core/configParser to learn the details

/*

port
sessionSecret

facebookClientId
facebookClientSecret
facebookCallbackUrl

*/

module.exports = new Map();
